name: Models Continuous Integration
on: [push]
jobs:
  build:
    runs-on: windows-latest
    strategy: 
      matrix:
       dotnet-version: ['6.0.x']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK 60
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Add Azure artifact
      run: |
        dotnet nuget locals all --clear
        dotnet nuget add source 'https://pkgs.dev.azure.com/e-LfH/_packaging/LearningHubFeed/nuget/v3/index.json' --name 'LearningHubFeed' --username 'kevin.whittaker' --password ${{ secrets.AZURE_DEVOPS_PAT }} --store-password-in-clear-text
        dotnet nuget list source

    - name: Restore dependencies
      run: dotnet restore

    - name: Build elfhHub models projects
      run: |
        dotnet build LearningHub.Nhs.Models.sln --configuration release

    #- name: Push generated package to GitHub registry         
    #  run: dotnet nuget push "**/bin/Release/*.nupkg"  --source https://nuget.pkg.github.com/TechnologyEnhancedLearning/index.json   --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate 
    
