name: Models Continuous Integration
on: [push]
jobs:
  build:
    env:
        BuildConfiguration: 'Release'
        DOTNET_ROLL_FORWARD: 'Major'
        SOLUTION: 'LearningHub.Nhs.Models.sln'
        name: Build and publish package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Use the desired version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration release

    - name: Test
      run: dotnet test --configuration $(BuildConfiguration)

    - name: Pack
      run: dotnet pack elfhHub.Nhs.Models/elfhHub.Nhs.Models.csproj LearningHub.Nhs.Models/LearningHub.Nhs.Models.csproj --no-build    
    
   
